# https://cloud.google.com/appengine/docs/standard/python3/config/appref


runtime: python37 # or another supported version
# entrypoint: gunicorn -b :$PORT --chdir app/ app.wsgi:application


# https://cloud.google.com/appengine/docs/standard#second-gen-runtimes
# instance_class: F4_1G
#
# env_variables:
#   BUCKET_NAME: "django_tut"

handlers:
# Matches requests to /images/... to files in static/images/...
# - url: /images
#   static_dir: static/images

# This configures Google App Engine to serve the files in the app's static directory.
- url: /static
  static_dir: static/

- url: /.*
  # secure: always
  # redirect_http_response_code: 301
  script: auto
